/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package facebookalerts;

import java.io.FileNotFoundException;
import java.io.IOException;
import facebookalerts.bootstrapper.Bootstrapper;

public class App {

    public static void main(String[] args)
            throws FileNotFoundException, ClassNotFoundException, IOException, InterruptedException {
        Bootstrapper bootstrapper = new Bootstrapper();
        bootstrapper.run();
    }
}