/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package facebookalerts;

import java.time.Instant;
import java.time.temporal.ChronoUnit;

import facebookalerts.Scraper.Scraper;

public class App {

    public static void main(String[] args) throws InterruptedException {

        String[] keywords = { "free" };
        Instant dateTime = Instant.now().minus(1, ChronoUnit.DAYS);

        Scraper scraper = new Scraper();
        scraper.getPosts("https://facebook.com", keywords, dateTime);
    }
}