/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package facebook.alerts;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;

public class App {

    public static void main(String[] args) throws InterruptedException {

        System.setProperty("webdriver.chrome.driver",
                System.getProperty("user.dir") + "/src/main/resources/chromedriver");

        ChromeOptions options = new ChromeOptions();
        options.addArguments("user-data-dir=./src/main/resources/chromeprofile", "profile-directory=Profile 1");
        WebDriver driver = new ChromeDriver(options);

        driver.get("https://facebook.com");

        Thread.sleep(5000);
        driver.close();
    }
}