/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package facebook.alerts;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

public class App {

    public static void main(String[] args) throws InterruptedException {

        System.setProperty("webdriver.chrome.driver",
                System.getProperty("user.dir") + "/src/main/resources/chromedriver");

        WebDriver driver = new ChromeDriver();

        driver.get("https://facebook.com");
        Thread.sleep(10000);
        driver.close();
    }
}
