package facebookalerts;
/*
* This Java source file was generated by the Gradle 'init' task.
*/

import org.junit.jupiter.api.Test;

import java.io.FileNotFoundException;
import java.io.IOException;

class AppTest {
    @Test
    void testMain() throws FileNotFoundException, ClassNotFoundException, InterruptedException, IOException {
        String[] args = null;
        App.main(args);
    }
}
